# main.py
import datetime
questions_and_answers = [
    {"question": "hi", "answer": "Hello! How can I assist you today?"},
    {"question": "hello", "answer": "Hi there! What can I do for you?"},
    {"question": "how are you", "answer": "I'm just a bot, but I'm here to help! How about you?"},
    {"question": "what's the time now", "answer": lambda: f"The current time is {datetime.datetime.now().strftime('%H:%M:%S')}."},
    {"question": "what is the date today", "answer": lambda: f"Today's date is {datetime.datetime.now().strftime('%Y-%m-%d')}."},
    {"question": "who are you", "answer": "I'm your chatbot assistant, here to answer your questions and help with information!"},
    {"question": "what can you do", "answer": "I can answer questions about blockchain, cryptocurrency, and general daily queries. Try asking me something!"},
    {"question": "good morning", "answer": "Good morning! I hope you have a fantastic day ahead!"},
    {"question": "good afternoon", "answer": "Good afternoon! How can I assist you today?"},
    {"question": "good evening", "answer": "Good evening! What would you like to know?"},
    {"question": "thank you", "answer": "You're welcome! Let me know if there's anything else you need."},
    {"question": "bye", "answer": "Goodbye! Have a great day!"},
    {"question": "What is Bitcoin?", "answer": "Bitcoin is a decentralized digital currency without a central bank or single administrator."},
    {"question": "What is Ethereum?", "answer": "Ethereum is a decentralized platform for building and running smart contracts."},
    {"question": "What is blockchain?", "answer": "Blockchain is a distributed ledger technology that ensures data integrity without a central authority."},
    {"question": "What is a smart contract?", "answer": "A smart contract is a self-executing contract with the terms of the agreement directly written into lines of code."},
    {"question": "How do you buy Bitcoin?", "answer": "You can buy Bitcoin on various cryptocurrency exchanges like Coinbase, Binance, or Kraken."},
    {"question": "What is the difference between Bitcoin and Ethereum?", "answer": "Bitcoin is a digital currency while Ethereum is a decentralized platform that allows smart contracts and decentralized applications."},
    {"question": "What is a wallet in cryptocurrency?", "answer": "A cryptocurrency wallet is a software application that allows you to store and manage your cryptocurrencies."},
    {"question": "What is the blockchain consensus mechanism?", "answer": "A consensus mechanism is a protocol that considers a transaction as legitimate and secure. Bitcoin uses Proof of Work (PoW), and Ethereum is transitioning to Proof of Stake (PoS)."},
    {"question": "What is Proof of Work?", "answer": "Proof of Work (PoW) is a consensus mechanism where miners must solve complex mathematical problems to validate transactions."},
    {"question": "What is Proof of Stake?", "answer": "Proof of Stake (PoS) is a consensus mechanism where validators are chosen to create new blocks based on the number of coins they hold."},
    {"question": "What are altcoins?", "answer": "Altcoins are any cryptocurrencies other than Bitcoin. Examples include Ethereum, Litecoin, and Ripple."},
    {"question": "What is a blockchain node?", "answer": "A node is a computer that participates in the blockchain network by validating transactions and maintaining the blockchain ledger."},
    {"question": "What is mining?", "answer": "Mining is the process of verifying transactions and adding them to the blockchain by solving cryptographic puzzles."},
    {"question": "What is gas in Ethereum?", "answer": "Gas is the unit used to measure the computational work required to execute operations on the Ethereum network."},
    {"question": "What is a decentralized application (DApp)?", "answer": "A decentralized application (DApp) is an application that runs on a blockchain network, such as Ethereum, and is not controlled by any central authority."},
    {"question": "What is the purpose of smart contracts?", "answer": "Smart contracts automate and enforce the terms of a contract using code on a blockchain, eliminating the need for intermediaries."},
    {"question": "What is a hard fork?", "answer": "A hard fork is a significant change to the blockchain protocol that makes previously invalid blocks and transactions valid, often resulting in a new cryptocurrency."},
    {"question": "What is a soft fork?", "answer": "A soft fork is a backward-compatible change to the blockchain protocol where new blocks are valid under the old rules, but some old blocks may be invalid."},
    {"question": "What is a token?", "answer": "A token is a digital asset created and stored on a blockchain, representing a value or a utility in a decentralized network."},
    {"question": "What is an ICO?", "answer": "An ICO (Initial Coin Offering) is a fundraising method where a cryptocurrency project sells tokens in exchange for capital to fund development."},
    {"question": "What is a security token?", "answer": "A security token is a cryptocurrency token that represents ownership or shares in a real-world asset like equity or property."},
    {"question": "What is a utility token?", "answer": "A utility token is a cryptocurrency used to access a specific service or function within a blockchain ecosystem, like gas on Ethereum."},
    {"question": "What is DeFi?", "answer": "DeFi (Decentralized Finance) refers to a set of financial services built on blockchain technology that operate without traditional intermediaries like banks."},
    {"question": "What is a DAO?", "answer": "A DAO (Decentralized Autonomous Organization) is an organization that operates through smart contracts on a blockchain, without central management."},
    {"question": "What is a stablecoin?", "answer": "A stablecoin is a cryptocurrency pegged to a stable asset, such as the US Dollar, to minimize price volatility."},
    {"question": "What is a private key?", "answer": "A private key is a secret cryptographic key that is used to sign transactions and access a user's cryptocurrency wallet."},
    {"question": "What is a public key?", "answer": "A public key is a cryptographic key that can be shared publicly and is used to receive cryptocurrency into a wallet."},
    {"question": "What is a cryptocurrency exchange?", "answer": "A cryptocurrency exchange is an online platform where users can buy, sell, and trade cryptocurrencies."},
    {"question": "What is a decentralized exchange (DEX)?", "answer": "A decentralized exchange (DEX) is a peer-to-peer exchange that allows users to trade cryptocurrencies directly without an intermediary."},
    {"question": "What is a centralized exchange (CEX)?", "answer": "A centralized exchange (CEX) is a platform that acts as an intermediary for cryptocurrency transactions, like Coinbase or Binance."},
    {"question": "What is liquidity in crypto?", "answer": "Liquidity refers to the ability to buy or sell an asset in the market without significantly affecting its price."},
    {"question": "What is slippage?", "answer": "Slippage is the difference between the expected price of a trade and the actual price at which the trade is executed."},
    {"question": "What is a market order?", "answer": "A market order is an order to buy or sell a cryptocurrency at the best available price in the market."},
    {"question": "What is a limit order?", "answer": "A limit order is an order to buy or sell a cryptocurrency at a specific price or better."},
    {"question": "What is a stop order?", "answer": "A stop order is an order to buy or sell a cryptocurrency when the price reaches a specified level."},
    {"question": "What is a candlestick chart?", "answer": "A candlestick chart is a type of financial chart used to track the price movement of a cryptocurrency over a period of time."},
    {"question": "What is a bear market?", "answer": "A bear market is a market characterized by a prolonged period of declining asset prices."},
    {"question": "What is a bull market?", "answer": "A bull market is a market characterized by a prolonged period of rising asset prices."},
    {"question": "What is FOMO?", "answer": "FOMO (Fear of Missing Out) is the anxiety that one might miss out on a profitable investment opportunity in cryptocurrency."},
    {"question": "What is FUD?", "answer": "FUD (Fear, Uncertainty, and Doubt) refers to the spread of negative or misleading information to manipulate market sentiment."},
    {"question": "What is a whale in crypto?", "answer": "A whale is a person or entity that holds a large amount of a particular cryptocurrency, often enough to influence its price."},
    {"question": "What is an airdrop?", "answer": "An airdrop is a method of distributing free tokens or coins to cryptocurrency holders, often as a promotional tool."},
    {"question": "What is staking?", "answer": "Staking is the process of holding and locking a cryptocurrency in a wallet to support the operations of a blockchain network, typically in Proof of Stake (PoS) systems."},
    {"question": "What is yield farming?", "answer": "Yield farming is a process where cryptocurrency holders lend their assets to liquidity pools in return for rewards or interest."},
    {"question": "What is a rug pull?", "answer": "A rug pull is a type of scam in which the developers of a cryptocurrency project abruptly withdraw all liquidity from the platform, leaving investors with worthless tokens."},
    {"question": "What is a 51% attack?", "answer": "A 51% attack occurs when a group of miners control more than 50% of a blockchain's mining power, enabling them to manipulate the blockchain's transactions."},
    {"question": "What is SegWit?", "answer": "SegWit (Segregated Witness) is a Bitcoin protocol upgrade designed to improve transaction speed and block size efficiency."},
    {"question": "What is lightning network?", "answer": "The Lightning Network is a second-layer solution for Bitcoin designed to enable faster and cheaper transactions off the main Bitcoin blockchain."},
    {"question": "What is a block in blockchain?", "answer": "A block is a data structure that contains a batch of transactions in a blockchain. It is linked to the previous block, creating the chain."},
    {"question": "What is consensus?", "answer": "Consensus is the process by which blockchain participants agree on the validity of transactions and blocks."},
    {"question": "What is a ledger?", "answer": "A ledger is a record of transactions. In blockchain, it is a distributed and immutable record maintained by all participants in the network."},
    {"question": "What is an oracle in blockchain?", "answer": "An oracle is a third-party service that provides external data to smart contracts, enabling them to interact with real-world information."},
    {"question": "What is tokenization?", "answer": "Tokenization is the process of converting ownership or rights to an asset into a digital token that can be traded on a blockchain."},
    {"question": "What is a blockchain explorer?", "answer": "A blockchain explorer is an online tool that allows users to view transactions and data on a blockchain network."},
    {"question": "What is Layer 2?", "answer": "Layer 2 refers to technologies that are built on top of a blockchain to improve scalability, reduce transaction costs, and increase speed."},
    {"question": "What is an NFT?", "answer": "An NFT (Non-Fungible Token) is a unique digital asset that represents ownership of a specific item, like art or collectibles, on a blockchain."},
    {"question": "What is a crypto token?", "answer": "A crypto token is a digital asset built on a blockchain that represents a specific utility or value within its ecosystem."},
    {"question": "What is tokenomics?", "answer": "Tokenomics refers to the study and design of the economic systems surrounding cryptocurrencies and tokens."},
    {"question": "What is an Initial DEX Offering (IDO)?", "answer": "An IDO is a fundraising event in which a cryptocurrency project sells tokens to the public through a decentralized exchange."},
    {"question": "What is liquidity mining?", "answer": "Liquidity mining is the process of earning rewards by providing liquidity to decentralized finance (DeFi) protocols."},
    {"question": "What is a cryptographic hash?", "answer": "A cryptographic hash is a mathematical function that converts data into a fixed-length string of characters, often used to verify the integrity of data."},
    {"question": "What is a private blockchain?", "answer": "A private blockchain is a blockchain network that restricts who can participate in the network and access its data."},
    {"question": "What is a public blockchain?", "answer": "A public blockchain is a blockchain network that allows anyone to participate and view its data."},
    {"question": "What is sharding?", "answer": "Sharding is a technique used to divide a blockchain into smaller, more manageable pieces (shards) to improve scalability."},
    {"question": "What is a cross-chain?", "answer": "A cross-chain is a technology that allows different blockchains to interact and transfer assets between each other."},
    {"question": "What is a smart contract?", "answer": "A smart contract audit is a process of reviewing and testing the code of a smart contract to identify vulnerabilities and ensure it functions correctly."},
    {"question": "What is cryptocurrency?", "answer": "Cryptocurrency is a digital or virtual currency that uses cryptography for security and operates on a decentralized network, usually a blockchain."},
    {"question": "How does cryptocurrency work?", "answer": "Cryptocurrency works on blockchain technology, where transactions are recorded on a distributed ledger. It uses cryptography to secure transactions and control the creation of new units."},
    {"question": "What is blockchain technology?", "answer": "Blockchain technology is a decentralized and distributed ledger system that records transactions in a secure and transparent manner."},
    {"question": "What is Bitcoin?", "answer": "Bitcoin is the first and most popular cryptocurrency, created in 2009 by an unknown person or group using the pseudonym Satoshi Nakamoto."},
    {"question": "What is Ethereum?", "answer": "Ethereum is a blockchain platform that enables the creation of decentralized applications (dApps) and smart contracts, using its native cryptocurrency, Ether (ETH)."},
    {"question": "What is a crypto wallet?", "answer": "A crypto wallet is a digital tool that allows users to store, send, and receive cryptocurrencies securely."},
    {"question": "What is a private key in cryptocurrency?", "answer": "A private key is a secure, unique code that allows access to your cryptocurrency holdings. It must be kept confidential."},
    {"question": "What is a public key in cryptocurrency?", "answer": "A public key is a cryptographic code that allows others to send cryptocurrency to your wallet."},
    {"question": "What is a decentralized network?", "answer": "A decentralized network operates without a central authority, distributing data and operations across multiple nodes."},
    {"question": "What are smart contracts?", "answer": "Smart contracts are self-executing contracts with terms written into code, enabling trustless transactions."},
    {"question": "What is mining in cryptocurrency?", "answer": "Mining is the process of validating transactions and adding them to the blockchain by solving complex mathematical problems."},
    {"question": "What is proof of work (PoW)?", "answer": "Proof of Work is a consensus mechanism where miners solve mathematical puzzles to validate transactions and secure the blockchain."},
    {"question": "What is proof of stake (PoS)?", "answer": "Proof of Stake is a consensus mechanism where validators are chosen based on the amount of cryptocurrency they hold and are willing to 'stake' as collateral."},
    {"question": "What are altcoins?", "answer": "Altcoins are any cryptocurrencies other than Bitcoin, such as Ethereum, Litecoin, and Ripple."},
    {"question": "What is the difference between Bitcoin and Ethereum?", "answer": "Bitcoin is primarily a digital currency, while Ethereum is a platform for decentralized applications and smart contracts."},
    {"question": "What is a cryptocurrency exchange?", "answer": "A cryptocurrency exchange is a platform where users can buy, sell, or trade cryptocurrencies."},
    {"question": "What are the risks of investing in cryptocurrency?", "answer": "Risks include price volatility, hacking, regulatory changes, and loss of private keys."},
    {"question": "What is a stablecoin?", "answer": "Stablecoins are cryptocurrencies pegged to stable assets like fiat currency to reduce price volatility."},
    {"question": "What is a decentralized application (dApp)?", "answer": "A dApp is an application that runs on a blockchain, enabling decentralized, trustless interactions."}
]

def answer_question(question):
    for qa in questions_and_answers:
        if question.lower() in qa['question'].lower():
            # If the answer is a callable (like a function), call it
            return qa['answer']() if callable(qa['answer']) else qa['answer']
    return "Sorry, I don't know the answer to that question."
